"""Initial migration

Revision ID: 490b3c32386e
Revises: 
Create Date: 2023-06-08 11:19:38.084721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490b3c32386e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
